#!/usr/bin/env python3
"""Derive the desktop runtime from the server Compose contract (requires PyYAML).
The only deployment is the existing backend. No native storage or task engine.
"""
import argparse
from pathlib import Path
import sys
import re
import yaml

def render(root):
    version = re.search(r'const BackendVersion = "([^"]+)"', (root / "desktop/internal/app/config.go").read_text()).group(1)
    compose = yaml.safe_load((root / "docker-compose.yml").read_text())
    services = compose["services"]
    services.pop("temporal-ui", None)
    services.pop("gpu-scheduler", None)
    images = {"api": "backend", "worker": "backend", "migrations": "migrations",
              "frontend": "frontend", "sandbox": "sandbox"}
    for name, service in services.items():
        service.pop("build", None)
        service.pop("container_name", None)
        service.pop("ports", None)
        service.pop("profiles", None)
        service["image"] = f"qraft-desktop/{images.get(name, name)}:{version}"
        service["pull_policy"] = "never"
        service["labels"] = {"io.qraft.desktop.owner": "${QRAFT_DESKTOP_OWNER:?client owner is required}"}
        env = service.get("environment", {})
        for key in list(env):
            if key.startswith("ANTHROPIC_"):
                env[key] = ""
        if name in ("api", "worker"):
            env["APP_DEV_MODE"] = "true"
            env["APP_ENV"] = "development"
            env["ALGOFORGE_EMBEDDING_ENABLED"] = "${ALGOFORGE_EMBEDDING_ENABLED:-false}"
            env["ALGOFORGE_EMBEDDING_API_KEY"] = ""
            env["ALGOFORGE_EMBEDDING_UI_ALLOW_PUBLIC"] = "true" # Outbound API configuration; the UI stays loopback-only.
    services["worker"]["depends_on"]["sandbox"] = {"condition": "service_healthy"}
    services["caddy"]["ports"] = ["127.0.0.1:${LOCAL_PORT:-18180}:80"]
    services["caddy"]["environment"] = {"DOMAIN": ":80"}
    services["caddy"]["healthcheck"] = {"test": ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/health"], "interval": "3s", "timeout": "3s", "retries": 20}
    # One public loopback listener; internal databases and execution have none.
    compose.pop("x-common-env", None)
    compose.pop("name", None)
    for kind in ("volumes", "networks"):
        for name, resource in compose.get(kind, {}).items():
            if resource is None:
                resource = compose[kind][name] = {}
            if resource.get("external") or resource.get("name"):
                raise ValueError(f"Desktop {kind} must be project-scoped: {name}")
            resource["labels"] = {"io.qraft.desktop.owner": "${QRAFT_DESKTOP_OWNER:?client owner is required}"}
    caddy = """{
    admin off
    auto_https off
}
:80 {
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        -Server
    }
    handle /health {
        reverse_proxy api:8080
    }
    handle /api/* {
        reverse_proxy api:8080 {
            transport http {
                dial_timeout 5s
                response_header_timeout 60s
            }
        }
    }
    handle {
        reverse_proxy frontend:3000
    }
    encode gzip
}
"""
    files = {
        "compose.yml": "# Generated by desktop/scripts/prepare-runtime.py. Do not edit.\n" + yaml.safe_dump(compose, sort_keys=False, allow_unicode=True),
        "deploy/caddy/Caddyfile": caddy,
    }
    for path in sorted((root / "deploy/initdb").glob("*.sql")):
        files["deploy/initdb/" + path.name] = path.read_text()
    return files

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    p.add_argument("--output", type=Path)
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    dest = a.output or a.root / "desktop/internal/app/runtime"
    for name, content in render(a.root).items():
        path = dest / name
        if a.check:
            if not path.exists() or path.read_text() != content:
                sys.exit(f"Runtime is stale: {name}; run prepare-runtime.py")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print("Desktop runtime matches the server contract." if a.check else "Desktop runtime generated.")

if __name__ == "__main__":
    main()
