INSERT INTO knowledge_points (subject, code, name, sort_order) VALUES
('c_language', 'cl_basic_syntax', '基础语法与数据类型', 10),
('c_language', 'cl_operator_expression', '运算符与表达式', 20),
('c_language', 'cl_control_flow', '控制流（if/switch/for/while）', 30),
('c_language', 'cl_function', '函数与作用域', 40),
('c_language', 'cl_array_basic', '数组基础', 50),
('c_language', 'cl_string', '字符串与字符数组', 60),
('c_language', 'cl_pointer_basic', '指针基础', 70),
('c_language', 'cl_pointer_advanced', '指针进阶（多级指针/函数指针）', 80),
('c_language', 'cl_struct_union', '结构体与联合', 90),
('c_language', 'cl_file_io', '文件 I/O', 100),
('c_language', 'cl_memory', '内存管理与 malloc/free', 110),
('c_language', 'cl_preprocessor', '预处理与宏', 120),
('data_structure_algorithm', 'dsa_linear_list', '顺序表与链表', 10),
('data_structure_algorithm', 'dsa_stack_queue', '栈与队列', 20),
('data_structure_algorithm', 'dsa_string_pattern', '字符串模式匹配（KMP/BM）', 30),
('data_structure_algorithm', 'dsa_tree_binary', '二叉树及其遍历', 40),
('data_structure_algorithm', 'dsa_tree_bst_avl', '二叉搜索树与平衡树', 50),
('data_structure_algorithm', 'dsa_heap', '堆与优先队列', 60),
('data_structure_algorithm', 'dsa_hash_table', '散列表', 70),
('data_structure_algorithm', 'dsa_graph_basic', '图的存储与遍历', 80),
('data_structure_algorithm', 'dsa_shortest_path', '最短路径', 90),
('data_structure_algorithm', 'dsa_mst', '最小生成树', 100),
('data_structure_algorithm', 'dsa_sort_basic', '基础排序', 110),
('data_structure_algorithm', 'dsa_sort_advanced', '进阶排序（快排/归并/堆排）', 120),
('data_structure_algorithm', 'dsa_search', '查找算法', 130),
('data_structure_algorithm', 'dsa_dp_basic', '动态规划基础', 140)
ON CONFLICT (code) DO UPDATE SET
    subject = EXCLUDED.subject,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order;
