package repository

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/Gingoo-TvT/Qraft/backend/internal/domain"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ProblemRepository provides data access operations for algorithm problems
// stored in PostgreSQL.
type ProblemRepository struct {
	db *pgxpool.Pool
}

// ErrReviewQuarantineProtected means the database refused to delete a problem
// because immutable automated-review evidence still references it.
var ErrReviewQuarantineProtected = errors.New("problem is protected by review quarantine evidence")

// ErrGenerationStandardEvidenceConflict means an immutable receipt binding is
// already bound to different content or a different final outcome.
var ErrGenerationStandardEvidenceConflict = errors.New("generation standard evidence binding conflicts with stored evidence")

// ErrPublicReleaseApprovalConflict means the current artifact cannot be loosened safely.
var ErrPublicReleaseApprovalConflict = errors.New("public release approval conflicts with current governance state")

const problemSelectColumns = `
	id, serial_number, title, statement, level, difficulty,
	COALESCE(one_line_hint, ''), COALESCE(detailed_solution, ''), tags,
	time_limit, memory_limit, COALESCE(source, ''), status, workflow_id,
	COALESCE(metadata_json, '{}'::jsonb), created_at, updated_at`

const createProblemQuery = `
	INSERT INTO problems (
		id, title, statement, level, difficulty,
		one_line_hint, detailed_solution, tags,
		time_limit, memory_limit, source, status, workflow_id,
		metadata_json, created_at, updated_at
	) VALUES (
		$1, $2, $3, $4, $5,
		$6, $7, $8,
		$9, $10, $11, $12, $13,
		$14, $15, $16
	) RETURNING serial_number`

const updateProblemQuery = `
	UPDATE problems SET
		title = $2,
		statement = $3,
		level = $4,
		difficulty = $5,
		one_line_hint = $6,
		detailed_solution = $7,
		tags = $8,
		time_limit = $9,
		memory_limit = $10,
		source = $11,
		status = $12,
		workflow_id = $13,
		metadata_json = $14,
		updated_at = $15
	WHERE id = $1`

// NewProblemRepository creates a new ProblemRepository backed by the given
// connection pool.
func NewProblemRepository(db *pgxpool.Pool) *ProblemRepository {
	return &ProblemRepository{db: db}
}

// ProblemFilter defines the criteria for querying problems. Nil pointer fields
// are treated as "no filter" for that dimension.
type ProblemFilter struct {
	Level              *domain.ProblemLevel
	MinDiff            *int
	MaxDiff            *int
	Tags               []string
	Status             *string
	ExcludeQuarantined bool
	ExcludeRejected    bool
	Limit              int
	Offset             int
	OrderBy            string
}

// ReviewQuarantineRecord is the immutable evidence persisted when automated
// review rejects a generated candidate.
type ReviewQuarantineRecord struct {
	ProblemID          uuid.UUID
	OperationKey       string
	Reason             string
	WorkflowID         string
	WorkflowRunID      string
	ReviewGateChangeID string
	ReviewGateVersion  int
	ReviewResultSHA256 string
	ReviewResultJSON   json.RawMessage
	ReviewText         string
	SourceAncestryJSON json.RawMessage
}

// PublicReleaseApprovalReport is the auditable result returned to the caller.
type PublicReleaseApprovalReport struct {
	ProblemID        uuid.UUID            `json:"problem_id"`
	ArtifactID       uuid.UUID            `json:"artifact_id"`
	ApprovalID       uuid.UUID            `json:"approval_id"`
	ApprovedBy       string               `json:"approved_by"`
	ApprovedAt       time.Time            `json:"approved_at"`
	ReleaseStatus    domain.ProblemStatus `json:"release_status"`
	QuarantineReason string               `json:"release_quarantine_reason,omitempty"`
}

// Create inserts a new problem into the database. The problem's ID, CreatedAt,
// and UpdatedAt fields must already be populated by the caller (typically the
// service layer).
func (r *ProblemRepository) Create(ctx context.Context, p *domain.Problem) error {
	// MetadataJSON is already json.RawMessage (raw bytes); no marshal needed.
	// serial_number is auto-generated by the database sequence.

	var serialNum int
	err := r.db.QueryRow(ctx, createProblemQuery,
		p.ID,
		p.Title,
		p.Statement,
		p.Level,
		p.Difficulty,
		p.OneLineHint,
		p.DetailedSolution,
		p.Tags,
		p.TimeLimit,
		p.MemoryLimit,
		p.Source,
		p.Status,
		nullableString(p.WorkflowID),
		p.MetadataJSON,
		p.CreatedAt,
		p.UpdatedAt,
	).Scan(&serialNum)
	if err != nil {
		return fmt.Errorf("inserting problem %s: %w", p.ID, err)
	}

	p.SerialNumber = fmt.Sprintf("%d", serialNum)
	return nil
}

// ExecRaw executes a raw SQL query. Used by activities that need to insert
// into tables without a dedicated repository (e.g., solutions).
func (r *ProblemRepository) ExecRaw(ctx context.Context, query string, args ...interface{}) error {
	_, err := r.db.Exec(ctx, query, args...)
	return err
}

// QueryRaw executes a raw SQL query and returns the result rows. The caller
// is responsible for closing the returned Rows.
func (r *ProblemRepository) QueryRaw(ctx context.Context, query string, args ...interface{}) (pgx.Rows, error) {
	return r.db.Query(ctx, query, args...)
}

// ListSolutionsByProblemID retrieves the source artefacts associated with a
// problem.  Main is ordered first so callers that only need the intended
// solution can select it deterministically; the remaining roles are retained
// for the code-viewer and validation tooling.
func (r *ProblemRepository) ListSolutionsByProblemID(ctx context.Context, problemID uuid.UUID) ([]*domain.Solution, error) {
	rows, err := r.db.Query(ctx, `
		SELECT id, problem_id, solution_type, language, source_code,
		       COALESCE(compile_status, ''), created_at
		FROM solutions
		WHERE problem_id = $1
		ORDER BY CASE solution_type
		           WHEN 'main' THEN 0
		           WHEN 'brute' THEN 1
		           ELSE 2
		         END, created_at ASC, id ASC`, problemID)
	if err != nil {
		return nil, fmt.Errorf("querying solutions for problem %s: %w", problemID, err)
	}
	defer rows.Close()

	var solutions []*domain.Solution
	for rows.Next() {
		solution := &domain.Solution{}
		if err := rows.Scan(
			&solution.ID,
			&solution.ProblemID,
			&solution.SolutionType,
			&solution.Language,
			&solution.SourceCode,
			&solution.CompileStatus,
			&solution.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("scanning solution for problem %s: %w", problemID, err)
		}
		solutions = append(solutions, solution)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating solutions for problem %s: %w", problemID, err)
	}
	return solutions, nil
}

type problemRowScanner interface {
	Scan(dest ...interface{}) error
}

func scanProblemRow(scanner problemRowScanner, p *domain.Problem) error {
	var workflowID sql.NullString
	if err := scanner.Scan(
		&p.ID,
		&p.SerialNumber,
		&p.Title,
		&p.Statement,
		&p.Level,
		&p.Difficulty,
		&p.OneLineHint,
		&p.DetailedSolution,
		&p.Tags,
		&p.TimeLimit,
		&p.MemoryLimit,
		&p.Source,
		&p.Status,
		&workflowID,
		&p.MetadataJSON,
		&p.CreatedAt,
		&p.UpdatedAt,
	); err != nil {
		return err
	}
	if workflowID.Valid {
		p.WorkflowID = &workflowID.String
	} else {
		p.WorkflowID = nil
	}
	return nil
}

func nullableString(value *string) interface{} {
	if value == nil {
		return nil
	}
	return *value
}

// GetByID retrieves a single problem by its unique identifier. Returns
// sql.ErrNoRows wrapped in a descriptive error if no matching problem exists.
func (r *ProblemRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Problem, error) {
	query := `SELECT ` + problemSelectColumns + ` FROM problems WHERE id = $1`

	p := &domain.Problem{}

	err := scanProblemRow(r.db.QueryRow(ctx, query, id), p)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("problem %s not found: %w", id, sql.ErrNoRows)
		}
		return nil, fmt.Errorf("querying problem %s: %w", id, err)
	}

	return p, nil
}

// GetByWorkflowID retrieves the problem persisted by one generation workflow.
// Generation jobs v1 produces exactly one candidate; ordering keeps lookup
// deterministic for older data where the database did not enforce uniqueness.
func (r *ProblemRepository) GetByWorkflowID(ctx context.Context, workflowID string) (*domain.Problem, error) {
	query := `SELECT ` + problemSelectColumns + ` FROM problems
		WHERE workflow_id = $1
		ORDER BY created_at DESC, id DESC
		LIMIT 1`

	p := &domain.Problem{}
	if err := scanProblemRow(r.db.QueryRow(ctx, query, workflowID), p); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("problem for workflow %s not found: %w", workflowID, sql.ErrNoRows)
		}
		return nil, fmt.Errorf("querying problem for workflow %s: %w", workflowID, err)
	}
	if err := r.enrichReviewQuarantineReasons(ctx, []*domain.Problem{p}); err != nil {
		return nil, err
	}
	return p, nil
}

// FindByTitle returns existing problems whose title matches exactly after
// trimming whitespace and folding case. It is used as a deterministic
// duplicate-title guard in the generation workflow.
func (r *ProblemRepository) FindByTitle(ctx context.Context, title string, limit int) ([]*domain.Problem, error) {
	title = strings.TrimSpace(title)
	if title == "" {
		return nil, nil
	}
	if limit <= 0 {
		limit = 5
	}

	query := findByTitleQuery()

	rows, err := r.db.Query(ctx, query, title, limit)
	if err != nil {
		return nil, fmt.Errorf("querying problems by title %q: %w", title, err)
	}
	defer rows.Close()

	var problems []*domain.Problem
	for rows.Next() {
		p := &domain.Problem{}
		if err := scanProblemRow(rows, p); err != nil {
			return nil, fmt.Errorf("scanning title match: %w", err)
		}
		problems = append(problems, p)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterating title matches: %w", err)
	}

	return problems, nil
}

func findByTitleQuery() string {
	return `SELECT ` + problemSelectColumns + ` FROM problems
				WHERE lower(btrim(title)) = lower(btrim($1))
				  AND status <> 'quarantined'
				  AND status <> 'rejected'
				  AND COALESCE(metadata_json ->> 'stale', 'false') <> 'true'
				  AND NOT EXISTS (
				      SELECT 1 FROM problem_quarantine_records quarantine
				      WHERE quarantine.problem_id = problems.id
				  )
				ORDER BY created_at DESC
				LIMIT $2`
}

// List retrieves a paginated, filtered list of problems along with the total
// count of matching records. The total count is useful for building pagination
// controls in the API layer.
func (r *ProblemRepository) List(ctx context.Context, filter ProblemFilter) ([]*domain.Problem, int, error) {
	conditions, args, argIdx := buildProblemListWhere(filter)

	whereClause := ""
	if len(conditions) > 0 {
		whereClause = "WHERE " + strings.Join(conditions, " AND ")
	}

	// Count query for total matching records.
	countQuery := fmt.Sprintf("SELECT COUNT(*) FROM problems %s", whereClause)
	var total int
	if err := r.db.QueryRow(ctx, countQuery, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("counting problems: %w", err)
	}

	// Determine ordering. Default to created_at DESC for a sensible default
	// that surfaces newly created problems first.
	orderBy := "created_at DESC"
	allowedOrders := map[string]string{
		"created_at": "created_at DESC",
		"difficulty": "difficulty ASC",
		"title":      "title ASC",
		"updated_at": "updated_at DESC",
	}
	if filter.OrderBy != "" {
		if o, ok := allowedOrders[filter.OrderBy]; ok {
			orderBy = o
		}
	}

	// Apply sane defaults for pagination to avoid unbounded result sets.
	limit := filter.Limit
	if limit <= 0 || limit > 100 {
		limit = 20
	}

	offset := filter.Offset
	if offset < 0 {
		offset = 0
	}

	dataQuery := fmt.Sprintf(`SELECT %s FROM problems
			%s
			ORDER BY %s
			LIMIT $%d OFFSET $%d`,
		problemSelectColumns, whereClause, orderBy, argIdx, argIdx+1)

	args = append(args, limit, offset)

	rows, err := r.db.Query(ctx, dataQuery, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("querying problems: %w", err)
	}
	defer rows.Close()

	var problems []*domain.Problem
	for rows.Next() {
		p := &domain.Problem{}

		if err := scanProblemRow(rows, p); err != nil {
			return nil, 0, fmt.Errorf("scanning problem row: %w", err)
		}

		problems = append(problems, p)
	}

	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterating problem rows: %w", err)
	}
	rows.Close()
	if err := r.enrichReviewQuarantineReasons(ctx, problems); err != nil {
		return nil, 0, err
	}

	return problems, total, nil
}

func (r *ProblemRepository) enrichReviewQuarantineReasons(
	ctx context.Context,
	problems []*domain.Problem,
) error {
	var ids []uuid.UUID
	byID := make(map[uuid.UUID]*domain.Problem)
	for _, problem := range problems {
		if problem != nil && problem.Status == domain.ProblemStatusQuarantined {
			ids = append(ids, problem.ID)
			byID[problem.ID] = problem
		}
	}
	if len(ids) == 0 {
		return nil
	}

	rows, err := r.db.Query(ctx, `
		SELECT problem_id, reason
		FROM problem_quarantine_records
		WHERE problem_id = ANY($1::uuid[])`, ids)
	if err != nil {
		return fmt.Errorf("querying review quarantine reasons: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var problemID uuid.UUID
		var reason string
		if err := rows.Scan(&problemID, &reason); err != nil {
			return fmt.Errorf("scanning review quarantine reason: %w", err)
		}
		problem := byID[problemID]
		if problem == nil {
			continue
		}
		problem.MetadataJSON, err = mergeReviewQuarantineReason(problem.MetadataJSON, reason)
		if err != nil {
			return fmt.Errorf("enriching review quarantine reason for problem %s: %w", problemID, err)
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating review quarantine reasons: %w", err)
	}
	return nil
}

func mergeReviewQuarantineReason(metadata json.RawMessage, reason string) (json.RawMessage, error) {
	if strings.TrimSpace(reason) == "" {
		return metadata, nil
	}
	values := make(map[string]interface{})
	if len(metadata) > 0 {
		if err := json.Unmarshal(metadata, &values); err != nil {
			return nil, err
		}
	}
	values["review_quarantine_reason"] = reason
	return json.Marshal(values)
}

func buildProblemListWhere(filter ProblemFilter) ([]string, []interface{}, int) {
	var conditions []string
	var args []interface{}
	argIdx := 1

	if filter.Level != nil {
		conditions = append(conditions, fmt.Sprintf("level = $%d", argIdx))
		args = append(args, *filter.Level)
		argIdx++
	}

	if filter.MinDiff != nil {
		conditions = append(conditions, fmt.Sprintf("difficulty >= $%d", argIdx))
		args = append(args, *filter.MinDiff)
		argIdx++
	}

	if filter.MaxDiff != nil {
		conditions = append(conditions, fmt.Sprintf("difficulty <= $%d", argIdx))
		args = append(args, *filter.MaxDiff)
		argIdx++
	}

	if len(filter.Tags) > 0 {
		conditions = append(conditions, fmt.Sprintf("tags && $%d", argIdx))
		args = append(args, filter.Tags)
		argIdx++
	}

	if filter.Status != nil {
		conditions = append(conditions, fmt.Sprintf("status = $%d", argIdx))
		args = append(args, *filter.Status)
		argIdx++
	}
	if filter.ExcludeQuarantined {
		conditions = append(conditions, "status <> 'quarantined'")
		conditions = append(conditions, `NOT EXISTS (
			SELECT 1 FROM problem_quarantine_records quarantine
			WHERE quarantine.problem_id = problems.id
		)`)
	}
	if filter.ExcludeRejected {
		conditions = append(conditions, "status <> 'rejected'")
	}
	return conditions, args, argIdx
}

// Update overwrites all mutable fields of an existing problem. The caller must
// set UpdatedAt to the current time before calling this method.
func (r *ProblemRepository) Update(ctx context.Context, p *domain.Problem) error {
	// MetadataJSON is already json.RawMessage (raw bytes); no marshal needed.
	// serial_number is not updated as it's auto-generated.

	result, err := r.db.Exec(ctx, updateProblemQuery,
		p.ID,
		p.Title,
		p.Statement,
		p.Level,
		p.Difficulty,
		p.OneLineHint,
		p.DetailedSolution,
		p.Tags,
		p.TimeLimit,
		p.MemoryLimit,
		p.Source,
		p.Status,
		nullableString(p.WorkflowID),
		p.MetadataJSON,
		p.UpdatedAt,
	)
	if err != nil {
		if isReviewQuarantineProtectionError(err) {
			return fmt.Errorf("updating problem %s: %w", p.ID, ErrReviewQuarantineProtected)
		}
		return fmt.Errorf("updating problem %s: %w", p.ID, err)
	}

	if result.RowsAffected() == 0 {
		return fmt.Errorf("problem %s not found: %w", p.ID, sql.ErrNoRows)
	}

	return nil
}

// Delete removes a problem from the database by its ID. Returns an error
// wrapping sql.ErrNoRows if no matching problem exists.
func (r *ProblemRepository) Delete(ctx context.Context, id uuid.UUID) error {
	query := `DELETE FROM problems WHERE id = $1`

	result, err := r.db.Exec(ctx, query, id)
	if err != nil {
		if isReviewQuarantineProtectionError(err) {
			return fmt.Errorf("deleting problem %s: %w", id, ErrReviewQuarantineProtected)
		}
		return fmt.Errorf("deleting problem %s: %w", id, err)
	}

	if result.RowsAffected() == 0 {
		return fmt.Errorf("problem %s not found: %w", id, sql.ErrNoRows)
	}

	return nil
}

// HasReviewQuarantine reports whether deleting the problem would destroy an
// immutable automated-review evidence record.
func (r *ProblemRepository) HasReviewQuarantine(ctx context.Context, id uuid.UUID) (bool, error) {
	var exists bool
	if err := r.db.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM problem_quarantine_records WHERE problem_id=$1
		)`, id).Scan(&exists); err != nil {
		return false, fmt.Errorf("checking review quarantine for problem %s: %w", id, err)
	}
	return exists, nil
}

// UpdateStatus changes the workflow status of a problem (e.g. "draft",
// "review", "published") without modifying any other fields.
func (r *ProblemRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	query := `
		UPDATE problems
		SET status = $2, updated_at = NOW()
		WHERE id = $1`

	result, err := r.db.Exec(ctx, query, id, status)
	if err != nil {
		if isReviewQuarantineProtectionError(err) {
			return fmt.Errorf("updating status for problem %s: %w", id, ErrReviewQuarantineProtected)
		}
		return fmt.Errorf("updating status for problem %s: %w", id, err)
	}

	if result.RowsAffected() == 0 {
		return fmt.Errorf("problem %s not found: %w", id, sql.ErrNoRows)
	}

	return nil
}

// AttachGenerationStandardEvidence binds an immutable receipt after the
// publication decision is final. It deliberately writes a separate table:
// problems.metadata_json is part of the governed problem content identity and
// must not change after the publication gate has finalized that identity.
func (r *ProblemRepository) AttachGenerationStandardEvidence(
	ctx context.Context,
	id uuid.UUID,
	binding domain.GenerationStandardEvidenceBinding,
) error {
	if err := binding.Validate(id.String()); err != nil {
		return fmt.Errorf("invalid generation standard evidence binding: %w", err)
	}

	result, err := r.db.Exec(
		ctx,
		generationStandardEvidenceAttachSQL(),
		id,
		binding.Reference.SchemaVersion,
		binding.Reference.SHA256,
		binding.Reference.Path,
		binding.FinalStatus,
		binding.QuarantineReason,
		binding.OutcomeCategory,
		binding.OutcomeKind,
		binding.OutcomeSHA256,
	)
	if err != nil {
		return fmt.Errorf("attaching generation standard evidence binding to problem %s: %w", id, err)
	}
	if result.RowsAffected() == 1 {
		return nil
	}

	stored, ok, getErr := r.GetGenerationStandardEvidence(ctx, id)
	if getErr != nil {
		return fmt.Errorf("checking generation standard evidence binding for problem %s: %w", id, getErr)
	}
	if ok && stored == binding {
		return nil
	}
	if !ok {
		problem, problemErr := r.GetByID(ctx, id)
		if problemErr != nil {
			return fmt.Errorf("checking generation standard evidence problem %s: %w", id, problemErr)
		}
		return fmt.Errorf("problem %s status %q did not accept final evidence status %q", id, problem.Status, binding.FinalStatus)
	}
	return fmt.Errorf("problem %s: %w", id, ErrGenerationStandardEvidenceConflict)
}

// GetGenerationStandardEvidence reads the immutable post-gate receipt binding.
func (r *ProblemRepository) GetGenerationStandardEvidence(
	ctx context.Context,
	id uuid.UUID,
) (domain.GenerationStandardEvidenceBinding, bool, error) {
	var binding domain.GenerationStandardEvidenceBinding
	err := r.db.QueryRow(ctx, `
SELECT schema_version, sha256, object_path, final_status, quarantine_reason,
       outcome_category, outcome_kind, outcome_sha256
FROM problem_generation_standard_evidence
WHERE problem_id = $1`, id).Scan(
		&binding.Reference.SchemaVersion,
		&binding.Reference.SHA256,
		&binding.Reference.Path,
		&binding.FinalStatus,
		&binding.QuarantineReason,
		&binding.OutcomeCategory,
		&binding.OutcomeKind,
		&binding.OutcomeSHA256,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return domain.GenerationStandardEvidenceBinding{}, false, nil
	}
	if err != nil {
		return domain.GenerationStandardEvidenceBinding{}, false, fmt.Errorf("getting generation standard evidence for problem %s: %w", id, err)
	}
	if err := binding.Validate(id.String()); err != nil {
		return domain.GenerationStandardEvidenceBinding{}, false, fmt.Errorf("invalid stored generation standard evidence for problem %s: %w", id, err)
	}
	return binding, true, nil
}

func generationStandardEvidenceAttachSQL() string {
	return `
INSERT INTO problem_generation_standard_evidence (
    problem_id, schema_version, sha256, object_path,
    final_status, quarantine_reason, outcome_category,
    outcome_kind, outcome_sha256
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
FROM problems
WHERE id = $1 AND status = $5::text
ON CONFLICT (problem_id) DO NOTHING`
}

func isReviewQuarantineProtectionError(err error) bool {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return false
	}
	return (pgErr.Code == "23503" && pgErr.ConstraintName == "problem_quarantine_records_problem_id_fkey") ||
		(pgErr.Code == "23514" && pgErr.ConstraintName == "problem_review_quarantine_status_immutable")
}

// ApprovePublicRelease turns an explicitly reviewed, quarantined definition
// artifact into a project-owned artifact and then re-runs the normal release
// gate. The append-only provenance ledger remains the source of audit truth.
func (r *ProblemRepository) ApprovePublicRelease(
	ctx context.Context,
	id uuid.UUID,
	actor string,
) (PublicReleaseApprovalReport, error) {
	actor = strings.TrimSpace(actor)
	if actor == "" {
		return PublicReleaseApprovalReport{}, fmt.Errorf("approval actor is required")
	}

	tx, err := r.db.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.Serializable})
	if err != nil {
		return PublicReleaseApprovalReport{}, fmt.Errorf("beginning public release approval transaction: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // rollback on committed tx is a no-op

	var currentStatus domain.ProblemStatus
	if err := tx.QueryRow(ctx, `
		SELECT status FROM problems WHERE id=$1 FOR UPDATE`, id).Scan(&currentStatus); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return PublicReleaseApprovalReport{}, fmt.Errorf("problem %s not found: %w", id, sql.ErrNoRows)
		}
		return PublicReleaseApprovalReport{}, fmt.Errorf("locking problem for release approval: %w", err)
	}
	if currentStatus != domain.ProblemStatusQuarantined &&
		currentStatus != domain.ProblemStatusPublished {
		return PublicReleaseApprovalReport{}, fmt.Errorf(
			"%w: problem status %s is not reviewable", ErrPublicReleaseApprovalConflict, currentStatus)
	}

	prerequisites, err := readPublicationGatePrerequisites(ctx, tx, id)
	if err != nil {
		return PublicReleaseApprovalReport{}, err
	}
	if reasons := prerequisites.blockingReasons(); len(reasons) > 0 {
		return PublicReleaseApprovalReport{}, fmt.Errorf("%w: %s", ErrPublicReleaseApprovalConflict, strings.Join(reasons, "; "))
	}

	var reviewQuarantined bool
	if err := tx.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM problem_quarantine_records WHERE problem_id=$1
		)`, id).Scan(&reviewQuarantined); err != nil {
		return PublicReleaseApprovalReport{}, fmt.Errorf("checking automated review quarantine: %w", err)
	}
	if reviewQuarantined {
		return PublicReleaseApprovalReport{}, ErrReviewQuarantineProtected
	}

	var artifactID uuid.UUID
	var licenseBasis string
	var takedownStatus string
	var policyVersion string
	var metadata json.RawMessage
	var termsSnapshotHash string
	if err := tx.QueryRow(ctx, `
		SELECT artifact.artifact_id, artifact.license_basis,
		       artifact.takedown_status, artifact.policy_version, artifact.metadata,
		       artifact.terms_snapshot_hash
		FROM provenance_artifact_bindings binding
		JOIN provenance_artifacts artifact ON artifact.artifact_id=binding.artifact_id
		WHERE binding.subject_type='problem'
		  AND binding.subject_id=$1
		  AND binding.artifact_role='definition'
		  AND binding.is_current
		FOR UPDATE OF binding, artifact`, id.String()).Scan(
		&artifactID, &licenseBasis, &takedownStatus, &policyVersion, &metadata,
		&termsSnapshotHash,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return PublicReleaseApprovalReport{}, fmt.Errorf("definition provenance binding not found: %w", ErrPublicReleaseApprovalConflict)
		}
		return PublicReleaseApprovalReport{}, fmt.Errorf("locking definition provenance artifact: %w", err)
	}

	report := PublicReleaseApprovalReport{
		ProblemID:  id,
		ArtifactID: artifactID,
		ApprovedBy: actor,
	}
	var existing struct {
		ApprovalID string `json:"approval_id"`
		ApprovedBy string `json:"approved_by"`
		ApprovedAt string `json:"approved_at"`
	}
	var approvalJSON string
	var snapshotHash string
	var metadataMap map[string]json.RawMessage
	if json.Unmarshal(metadata, &metadataMap) == nil {
		if raw, ok := metadataMap["operator_public_release_approval"]; ok {
			_ = json.Unmarshal(raw, &existing)
			approvalJSON = string(raw)
		}
	}

	if takedownStatus == "active" {
		if licenseBasis != "project_owned" {
			return report, fmt.Errorf("%w: active artifact license basis is %s", ErrPublicReleaseApprovalConflict, licenseBasis)
		}
		snapshotHash = termsSnapshotHash
		if parsed, parseErr := uuid.Parse(existing.ApprovalID); parseErr == nil {
			report.ApprovalID = parsed
		}
		if existing.ApprovedBy != "" {
			report.ApprovedBy = existing.ApprovedBy
		}
		if parsed, parseErr := time.Parse(time.RFC3339Nano, existing.ApprovedAt); parseErr == nil {
			report.ApprovedAt = parsed
		}
	} else {
		if takedownStatus != "quarantined_unknown" || licenseBasis != "unknown" {
			return report, fmt.Errorf("%w: artifact state is %s/%s", ErrPublicReleaseApprovalConflict, licenseBasis, takedownStatus)
		}

		report.ApprovalID = uuid.New()
		report.ApprovedAt = time.Now().UTC()
		approvalDocument, err := json.Marshal(map[string]interface{}{
			"approval_id": report.ApprovalID.String(),
			"problem_id":  id.String(),
			"artifact_id": artifactID.String(),
			"approved_by": actor,
			"approved_at": report.ApprovedAt.Format(time.RFC3339Nano),
			"decision":    "approved_for_public_release",
		})
		if err != nil {
			return report, fmt.Errorf("encoding release approval: %w", err)
		}
		digest := sha256.Sum256(approvalDocument)
		snapshotHash = hex.EncodeToString(digest[:])
		snapshotURI := "algoforge://operator-public-release-approval/" + report.ApprovalID.String()

		if _, err := tx.Exec(ctx, insertOperatorTermsSnapshotSQL(),
			snapshotHash, snapshotURI, report.ApprovedAt, actor, approvalDocument); err != nil {
			return report, fmt.Errorf("recording unreviewed release terms snapshot: %w", err)
		}
		if _, err := tx.Exec(ctx, approveOperatorTermsSnapshotSQL(), snapshotHash); err != nil {
			return report, fmt.Errorf("approving release terms snapshot: %w", err)
		}
		var snapshotReviewStatus string
		if err := tx.QueryRow(ctx, `
			SELECT review_status FROM provenance_terms_snapshots WHERE snapshot_hash=$1`,
			snapshotHash).Scan(&snapshotReviewStatus); err != nil {
			return report, fmt.Errorf("verifying approved release terms snapshot: %w", err)
		}
		if snapshotReviewStatus != "approved" {
			return report, fmt.Errorf(
				"%w: terms snapshot review status is %s",
				ErrPublicReleaseApprovalConflict, snapshotReviewStatus)
		}

		approvalJSON = string(approvalDocument)
	}

	if report.ApprovalID == uuid.Nil || report.ApprovedAt.IsZero() {
		return report, fmt.Errorf("%w: active artifact is missing approval evidence", ErrPublicReleaseApprovalConflict)
	}
	if _, err := tx.Exec(ctx, applyOperatorApprovalToLineageSQL(),
		artifactID, snapshotHash, approvalJSON, report.ApprovedBy); err != nil {
		return report, fmt.Errorf("applying release governance approval to artifact lineage: %w", err)
	}
	var lineageAllowed bool
	if err := tx.QueryRow(ctx,
		`SELECT provenance_artifact_use_allowed($1, 'public_release')`,
		artifactID).Scan(&lineageAllowed); err != nil {
		return report, fmt.Errorf("checking approved artifact lineage: %w", err)
	}
	if !lineageAllowed {
		return report, fmt.Errorf("%w: artifact lineage is not eligible for public release", ErrPublicReleaseApprovalConflict)
	}
	if err := tx.Commit(ctx); err != nil {
		return report, fmt.Errorf("committing public release approval: %w", err)
	}

	operationKey := "operator-public-release:" + report.ApprovalID.String() + ":gate-v2"
	report.ReleaseStatus, report.QuarantineReason, err = r.ApplyPublicReleaseGate(ctx, id, operationKey)
	if err != nil {
		return report, fmt.Errorf("re-running publication gate after approval: %w", err)
	}
	return report, nil
}

func insertOperatorTermsSnapshotSQL() string {
	return `
INSERT INTO provenance_terms_snapshots (
    snapshot_hash, source, snapshot_uri, effective_at, captured_at,
    reviewer, review_status, metadata
) VALUES (
    $1, 'operator_public_release_approval', $2, $3, $3,
    $4, 'unreviewed', $5::jsonb
)
ON CONFLICT (snapshot_hash) DO NOTHING`
}

func approveOperatorTermsSnapshotSQL() string {
	return `
UPDATE provenance_terms_snapshots
SET review_status='approved'
WHERE snapshot_hash=$1
  AND review_status='unreviewed'`
}

func applyOperatorApprovalToLineageSQL() string {
	return `
WITH RECURSIVE lineage AS (
    SELECT artifact_id FROM provenance_artifacts WHERE artifact_id=$1
    UNION
    SELECT ancestry.parent_artifact_id
    FROM lineage
    JOIN provenance_artifact_ancestry ancestry
      ON ancestry.child_artifact_id=lineage.artifact_id
), updated AS (
    UPDATE provenance_artifacts artifact
    SET license_basis='project_owned',
        terms_snapshot_hash=$2,
        takedown_status='active',
        internal_eval_allowed=TRUE,
        private_training_allowed=FALSE,
        public_release_allowed=TRUE,
        metadata=COALESCE(artifact.metadata, '{}'::jsonb) || jsonb_build_object(
            'ownership_record', 'administrator approved project ownership and public release rights',
            'terms_snapshot', $2::text,
            'operator_public_release_approval', $3::jsonb
        )
    WHERE artifact.artifact_id IN (SELECT artifact_id FROM lineage)
      AND artifact.takedown_status='quarantined_unknown'
      AND artifact.license_basis='unknown'
    RETURNING artifact.artifact_id, artifact.policy_version
)
INSERT INTO provenance_audit_events (
    artifact_id, event_type, actor, reason, policy_version, details
)
SELECT artifact_id, 'operator_public_release_approved', $4,
       'administrator approved public release', policy_version, $3::jsonb
FROM updated`
}

// ApplyPublicReleaseGate evaluates the current provenance binding and changes
// publication status in the same serializable transaction. A policy denial is
// a successful quarantine transition, not an infrastructure error.
func (r *ProblemRepository) ApplyPublicReleaseGate(ctx context.Context, id uuid.UUID, operationKey string) (domain.ProblemStatus, string, error) {
	if strings.TrimSpace(operationKey) == "" {
		return "", "", fmt.Errorf("publication gate operation key is required")
	}
	tx, err := r.db.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.Serializable})
	if err != nil {
		return "", "", fmt.Errorf("beginning public release gate transaction: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // rollback on committed tx is a no-op

	prerequisites, err := readPublicationGatePrerequisites(ctx, tx, id)
	if err != nil {
		return "", "", err
	}

	var artifactID uuid.UUID
	var policyVersion string
	var allowed bool
	err = tx.QueryRow(ctx, `
		SELECT binding.artifact_id, artifact.policy_version,
		       provenance_artifact_use_allowed(binding.artifact_id, 'public_release')
		FROM provenance_artifact_bindings binding
		JOIN provenance_artifacts artifact ON artifact.artifact_id = binding.artifact_id
		WHERE binding.subject_type = 'problem'
		  AND binding.subject_id = $1
		  AND binding.artifact_role = 'definition'
		  AND binding.is_current
		FOR SHARE OF binding, artifact`, id.String()).Scan(&artifactID, &policyVersion, &allowed)

	bindingFound := true
	if errors.Is(err, pgx.ErrNoRows) {
		bindingFound = false
		artifactID = uuid.Nil
		policyVersion = ""
	} else if err != nil {
		return "", "", fmt.Errorf("evaluating public release provenance gate: %w", err)
	}
	status, reason := publicationGateDecision(bindingFound, allowed, prerequisites.blockingReasons()...)

	tag, err := tx.Exec(ctx, updateProblemPublicationGateSQL(), id, status, policyVersion, reason)
	if err != nil {
		return "", "", fmt.Errorf("applying problem publication status: %w", err)
	}
	if tag.RowsAffected() != 1 {
		return "", "", fmt.Errorf("problem %s not found while applying publication gate: %w", id, sql.ErrNoRows)
	}

	eventType := "publication_gate_passed"
	eventReason := "public_release provenance gate passed"
	if status == domain.ProblemStatusQuarantined {
		eventType = "publication_gate_denied"
		eventReason = reason
	}
	var auditArtifact interface{}
	var auditPolicy interface{}
	if artifactID != uuid.Nil {
		auditArtifact = artifactID
	}
	if policyVersion != "" {
		auditPolicy = policyVersion
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO provenance_audit_events (
			artifact_id, event_type, actor, reason, policy_version, details
		)
		SELECT $1,$2,'store_problem_activity',$3,$4,
		       jsonb_build_object(
		           'problem_id',$5::text,
		           'requested_purpose','public_release',
		           'result_status',$6::text,
		           'operation_key',$7::text
		       )
		WHERE NOT EXISTS (
			SELECT 1 FROM provenance_audit_events
			WHERE event_type=$2
			  AND actor='store_problem_activity'
			  AND details->>'problem_id'=$5::text
			  AND details->>'operation_key'=$7::text
		)`,
		auditArtifact, eventType, eventReason, auditPolicy, id.String(), string(status), operationKey); err != nil {
		return "", "", fmt.Errorf("recording publication gate audit event: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO workflow_outbox (
			operation_key, event_type, aggregate_type, aggregate_id, payload_json
		) VALUES (
			$1::text, 'problem.publication_decided', 'problem', $2::text,
			jsonb_build_object(
				'problem_id',$2::text,
				'status',$3::text,
				'quarantine_reason',NULLIF($4::text,''),
				'publication_policy_version',$5::text
			)
		)
		ON CONFLICT (operation_key, event_type) DO NOTHING`,
		operationKey, id.String(), string(status), reason, auditPolicy); err != nil {
		return "", "", fmt.Errorf("enqueueing problem publication outbox event: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return "", "", fmt.Errorf("committing public release gate: %w", err)
	}
	return status, reason, nil
}

type publicationGatePrerequisites struct {
	HasDetailedSolution      bool
	HasMainSolution          bool
	HasBruteSolution         bool
	HasRunnableTestcases     bool
	HasActiveStatementVector bool
	ProblemFresh             bool
	ActiveStatementFresh     bool
	SolutionsFresh           bool
	TestcasesFresh           bool
}

func readPublicationGatePrerequisites(ctx context.Context, tx pgx.Tx, id uuid.UUID) (publicationGatePrerequisites, error) {
	var checks publicationGatePrerequisites
	err := tx.QueryRow(ctx, publicationGatePrerequisitesSQL(), id).Scan(
		&checks.HasDetailedSolution,
		&checks.HasMainSolution,
		&checks.HasBruteSolution,
		&checks.HasRunnableTestcases,
		&checks.HasActiveStatementVector,
		&checks.ProblemFresh,
		&checks.ActiveStatementFresh,
		&checks.SolutionsFresh,
		&checks.TestcasesFresh,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return checks, fmt.Errorf("problem %s not found while evaluating publication prerequisites: %w", id, sql.ErrNoRows)
	}
	if err != nil {
		return checks, fmt.Errorf("evaluating publication prerequisites: %w", err)
	}
	return checks, nil
}

func (p publicationGatePrerequisites) blockingReasons() []string {
	var reasons []string
	if !p.HasDetailedSolution {
		reasons = append(reasons, "missing detailed solution")
	}
	if !p.HasMainSolution {
		reasons = append(reasons, "missing successful main solution")
	}
	if !p.HasBruteSolution {
		reasons = append(reasons, "missing successful brute solution")
	}
	if !p.HasRunnableTestcases {
		reasons = append(reasons, "missing runnable test artifacts")
	}
	if !p.HasActiveStatementVector {
		reasons = append(reasons, "missing current active statement vector")
	}
	if !p.ProblemFresh {
		reasons = append(reasons, "problem edit refresh is stale")
	}
	if !p.ActiveStatementFresh {
		reasons = append(reasons, "current active statement vector is stale")
	}
	if !p.SolutionsFresh {
		reasons = append(reasons, "solution artifacts are stale")
	}
	if !p.TestcasesFresh {
		reasons = append(reasons, "test artifacts are stale")
	}
	return reasons
}

func publicationGatePrerequisitesSQL() string {
	return `
SELECT
    btrim(COALESCE(p.detailed_solution, '')) <> '',
    EXISTS (
        SELECT 1
        FROM solutions s
        WHERE s.problem_id = p.id
          AND s.solution_type = 'main'
          AND s.compile_status = 'success'
          AND btrim(s.source_code) <> ''
          AND COALESCE(s.metadata_json ->> 'stale', 'false') <> 'true'
    ),
    EXISTS (
        SELECT 1
        FROM solutions s
        WHERE s.problem_id = p.id
          AND s.solution_type = 'brute'
          AND s.compile_status = 'success'
          AND btrim(s.source_code) <> ''
          AND COALESCE(s.metadata_json ->> 'stale', 'false') <> 'true'
    ),
    EXISTS (
        SELECT 1
        FROM testcases tc
        WHERE tc.problem_id = p.id
          AND btrim(tc.input_path) <> ''
          AND btrim(tc.output_path) <> ''
          AND COALESCE(tc.metadata_json ->> 'stale', 'false') <> 'true'
    ),
    EXISTS (
        SELECT 1
        FROM embedding_active_pointers active
        INNER JOIN problem_embeddings pe
          ON pe.model_version_id = active.model_version_id
         AND pe.embedding_kind = active.embedding_kind
        WHERE active.embedding_kind = 'statement'
          AND pe.problem_id = p.id
          AND pe.content_hash = embedding_statement_content_hash(p.title, p.statement, p.one_line_hint)
          AND COALESCE(pe.metadata_json ->> 'stale', 'false') <> 'true'
    ),
    COALESCE(p.metadata_json ->> 'stale', 'false') <> 'true',
    NOT EXISTS (
        SELECT 1
        FROM embedding_active_pointers active
        INNER JOIN problem_embeddings pe
          ON pe.model_version_id = active.model_version_id
         AND pe.embedding_kind = active.embedding_kind
        WHERE active.embedding_kind = 'statement'
          AND pe.problem_id = p.id
          AND pe.content_hash = embedding_statement_content_hash(p.title, p.statement, p.one_line_hint)
          AND COALESCE(pe.metadata_json ->> 'stale', 'false') = 'true'
    ),
    NOT EXISTS (
        SELECT 1
        FROM solutions s
        WHERE s.problem_id = p.id
          AND COALESCE(s.metadata_json ->> 'stale', 'false') = 'true'
    ),
    NOT EXISTS (
        SELECT 1
        FROM testcases tc
        WHERE tc.problem_id = p.id
          AND COALESCE(tc.metadata_json ->> 'stale', 'false') = 'true'
    )
FROM problems p
WHERE p.id = $1
FOR SHARE OF p`
}

func updateProblemPublicationGateSQL() string {
	return `
UPDATE problems
SET status = $2::text,
    metadata_json = jsonb_strip_nulls(
        COALESCE(metadata_json, '{}'::jsonb) ||
        jsonb_build_object(
            'publication_gate_version', '2026-08-16.t10',
            'publication_policy_version', NULLIF($3::text, ''),
            'publication_gate_status', $2::text,
            'publication_quarantine_reason', NULLIF($4::text, '')
        )
    ),
    updated_at = NOW()
WHERE id = $1`
}

// ApplyReviewQuarantine atomically isolates a problem and records the complete
// automated-review evidence. Reusing an operation key is allowed only for the
// exact same problem and review payload.
func (r *ProblemRepository) ApplyReviewQuarantine(
	ctx context.Context,
	record ReviewQuarantineRecord,
) (domain.ProblemStatus, string, error) {
	if err := validateReviewQuarantineRecord(record); err != nil {
		return "", "", err
	}

	tx, err := r.db.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.Serializable})
	if err != nil {
		return "", "", fmt.Errorf("beginning review quarantine transaction: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // rollback on committed tx is a no-op

	tag, err := tx.Exec(ctx, `
		INSERT INTO problem_quarantine_records (
			problem_id, operation_key, reason, workflow_id, workflow_run_id,
			review_gate_change_id, review_gate_version, review_result_sha256,
			review_result, review_text, source_ancestry
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
		ON CONFLICT (operation_key) DO NOTHING`,
		record.ProblemID, record.OperationKey, record.Reason,
		record.WorkflowID, record.WorkflowRunID, record.ReviewGateChangeID,
		record.ReviewGateVersion, record.ReviewResultSHA256,
		record.ReviewResultJSON, record.ReviewText, record.SourceAncestryJSON,
	)
	if err != nil {
		return "", "", fmt.Errorf("recording problem review quarantine: %w", err)
	}
	if tag.RowsAffected() == 0 {
		var existingProblemID uuid.UUID
		var existingReason, existingHash, existingWorkflowID, existingRunID, existingChangeID string
		var existingVersion int
		var sameReview, sameReviewText, sameAncestry bool
		if err := tx.QueryRow(ctx, `
			SELECT problem_id, reason, review_result_sha256, workflow_id, workflow_run_id,
			       review_gate_change_id, review_gate_version,
			       review_result=$2::jsonb, review_text=$3::text,
			       source_ancestry=$4::jsonb
			FROM problem_quarantine_records
			WHERE operation_key=$1
			FOR SHARE`, record.OperationKey, record.ReviewResultJSON, record.ReviewText, record.SourceAncestryJSON).Scan(
			&existingProblemID, &existingReason, &existingHash, &existingWorkflowID, &existingRunID,
			&existingChangeID, &existingVersion, &sameReview, &sameReviewText, &sameAncestry,
		); err != nil {
			return "", "", fmt.Errorf("reading idempotent review quarantine: %w", err)
		}
		if existingProblemID != record.ProblemID ||
			existingReason != record.Reason ||
			existingHash != record.ReviewResultSHA256 ||
			existingWorkflowID != record.WorkflowID ||
			existingRunID != record.WorkflowRunID ||
			existingChangeID != record.ReviewGateChangeID ||
			existingVersion != record.ReviewGateVersion ||
			!sameReview || !sameReviewText || !sameAncestry {
			return "", "", fmt.Errorf("review quarantine operation key %q was already used with different evidence", record.OperationKey)
		}
	}

	status := domain.ProblemStatusQuarantined
	tag, err = tx.Exec(ctx, `UPDATE problems SET status=$2, updated_at=NOW() WHERE id=$1`, record.ProblemID, status)
	if err != nil {
		return "", "", fmt.Errorf("applying review quarantine status: %w", err)
	}
	if tag.RowsAffected() != 1 {
		return "", "", fmt.Errorf("problem %s not found while applying review quarantine: %w", record.ProblemID, sql.ErrNoRows)
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO workflow_outbox (
			operation_key, event_type, aggregate_type, aggregate_id, payload_json
		) VALUES (
			$1::text, 'problem.review_quarantined', 'problem', $2::text,
			jsonb_build_object(
				'problem_id',$2::text,
				'status',$3::text,
				'quarantine_reason',$4::text,
				'workflow_id',$5::text,
				'workflow_run_id',$6::text,
				'review_gate_change_id',$7::text,
				'review_gate_version',$8::integer,
				'review_result_sha256',$9::text
			)
		)
		ON CONFLICT (operation_key, event_type) DO NOTHING`,
		record.OperationKey, record.ProblemID.String(), string(status), record.Reason,
		record.WorkflowID, record.WorkflowRunID, record.ReviewGateChangeID,
		record.ReviewGateVersion, record.ReviewResultSHA256,
	); err != nil {
		return "", "", fmt.Errorf("enqueueing review quarantine outbox event: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return "", "", fmt.Errorf("committing review quarantine: %w", err)
	}
	return status, record.Reason, nil
}

func validateReviewQuarantineRecord(record ReviewQuarantineRecord) error {
	for name, value := range map[string]string{
		"operation key":         record.OperationKey,
		"reason":                record.Reason,
		"workflow ID":           record.WorkflowID,
		"workflow run ID":       record.WorkflowRunID,
		"review gate change ID": record.ReviewGateChangeID,
		"review text":           record.ReviewText,
	} {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s is required for review quarantine", name)
		}
	}
	if record.ProblemID == uuid.Nil {
		return fmt.Errorf("problem ID is required for review quarantine")
	}
	if record.ReviewGateVersion < 2 {
		return fmt.Errorf("review gate version %d cannot create v2 quarantine evidence", record.ReviewGateVersion)
	}
	if !json.Valid(record.ReviewResultJSON) {
		return fmt.Errorf("review result must be valid JSON")
	}
	digest := sha256.Sum256(record.ReviewResultJSON)
	if hex.EncodeToString(digest[:]) != record.ReviewResultSHA256 {
		return fmt.Errorf("review result SHA-256 does not match review JSON")
	}
	var review map[string]interface{}
	if err := json.Unmarshal(record.ReviewResultJSON, &review); err != nil {
		return fmt.Errorf("decoding review result: %w", err)
	}
	for _, field := range []string{
		"approved", "issues", "suggestions", "confidence", "estimated_difficulty",
		"is_duplicate", "duplicate_of", "duplicate_reason", "source_artifacts", "full_text",
	} {
		if _, ok := review[field]; !ok {
			return fmt.Errorf("review result is missing %q", field)
		}
	}
	if fullText, _ := review["full_text"].(string); fullText != record.ReviewText {
		return fmt.Errorf("review text does not match review result full_text")
	}
	var ancestry interface{}
	if err := json.Unmarshal(record.SourceAncestryJSON, &ancestry); err != nil {
		return fmt.Errorf("source ancestry must be a JSON array: %w", err)
	}
	ancestryList, ok := ancestry.([]interface{})
	if !ok || len(ancestryList) == 0 {
		return fmt.Errorf("source ancestry must be a non-empty JSON array")
	}
	if !reflect.DeepEqual(review["source_artifacts"], ancestry) {
		return fmt.Errorf("source ancestry does not match review result source_artifacts")
	}
	return nil
}

func publicationGateDecision(bindingFound, allowed bool, blockingReasons ...string) (domain.ProblemStatus, string) {
	var reasons []string
	if !bindingFound {
		reasons = append(reasons, "missing current problem provenance binding")
	}
	if bindingFound && !allowed {
		reasons = append(reasons, "public_release denied by current provenance policy")
	}
	for _, reason := range blockingReasons {
		if trimmed := strings.TrimSpace(reason); trimmed != "" {
			reasons = append(reasons, trimmed)
		}
	}
	if len(reasons) > 0 {
		return domain.ProblemStatusQuarantined, strings.Join(reasons, "; ")
	}
	return domain.ProblemStatusPublished, ""
}
